# Generated by Django 2.1 on 2018-12-04 11:49

import articles.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=20, verbose_name='分类')),
                ('parent_cate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='articles.Category', verbose_name='父级分类')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('excerpt', models.CharField(blank=True, default='', max_length=200, verbose_name='摘要')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('downloadable', models.BooleanField(default=False, verbose_name='是否可下载')),
                ('official_website', models.URLField(blank=True, max_length=100, null=True, verbose_name='软件官网')),
                ('app_size', models.FloatField(blank=True, max_length=20, null=True, verbose_name='应用大小')),
                ('size_unit', models.CharField(blank=True, choices=[('m', 'MB'), ('g', 'GB')], max_length=4, null=True, verbose_name='单位')),
                ('app_version', models.CharField(blank=True, max_length=20, null=True, verbose_name='应用版本')),
                ('official_download', models.URLField(blank=True, null=True, verbose_name='官方下载地址')),
                ('baidu_download', models.URLField(blank=True, null=True, verbose_name='百度网盘下载地址')),
                ('baidu_password', models.CharField(blank=True, max_length=20, null=True, verbose_name='百度网盘密码')),
                ('author', models.ForeignKey(default=articles.models.get_default_user, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('category', models.ForeignKey(default=articles.models.get_default_category, on_delete=django.db.models.deletion.SET_DEFAULT, to='articles.Category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='SystemRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('name', models.CharField(default='', max_length=20, verbose_name='软件系统要求')),
            ],
            options={
                'verbose_name': '软件系统要求',
                'verbose_name_plural': '软件系统要求',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('name', models.CharField(default='', max_length=20, verbose_name='标签')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='system_requirement',
            field=models.ManyToManyField(blank=True, to='articles.SystemRequirement', verbose_name='系统要求'),
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, to='articles.Tag', verbose_name='标签'),
        ),
    ]
