# Generated by Django 2.1 on 2018-12-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20181204_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='custom_uri',
            field=models.CharField(default='', max_length=100, verbose_name='自定义链接'),
        ),
    ]
