# Generated by Django 2.1 on 2018-12-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_post_custom_uri'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='custom_uri',
            new_name='short_title',
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='摘要'),
        ),
    ]
