# Generated by Django 2.1 on 2018-12-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20181204_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_title',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='自定义链接'),
        ),
    ]
