# Generated by Django 2.1 on 2018-12-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20181204_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='others_download_1',
            field=models.URLField(blank=True, null=True, verbose_name='其他下载地址1'),
        ),
        migrations.AddField(
            model_name='post',
            name='others_download_2',
            field=models.URLField(blank=True, null=True, verbose_name='其他下载地址2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='baidu_download',
            field=models.URLField(blank=True, null=True, verbose_name='下载地址'),
        ),
    ]
