# Generated by Django 2.1 on 2018-12-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20181205_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='short_name',
            field=models.CharField(max_length=30, unique=True, verbose_name='自定义链接'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_title',
            field=models.CharField(max_length=100, unique=True, verbose_name='自定义链接'),
        ),
    ]
