# Generated by Django 2.1 on 2018-12-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20181205_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favs',
            field=models.IntegerField(default=0, verbose_name='收藏数'),
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0, verbose_name='阅读数'),
        ),
    ]
