# Generated by Django 2.1 on 2018-12-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20181205_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='posts/%Y/%m', verbose_name='缩略图'),
        ),
    ]
