# Generated by Django 2.1 on 2018-12-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20181212_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in_nav',
            field=models.BooleanField(default=False, verbose_name='是否显示在首页次导航中'),
        ),
    ]
