# Generated by Django 2.1 on 2018-12-17 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20181214_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='top_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply', to='comments.Comments', verbose_name='顶级评论'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.TextField(verbose_name='评论内容'),
        ),
    ]
