# Generated by Django 2.1 on 2018-12-17 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20181217_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='top_comment',
            new_name='reply_to',
        ),
    ]
